### ISSUE TITLE
Intel 64 bit support

### ISSUE THREAD

**Issue by deet** [alexsorokoletov/MTStatusBarOverlay-Bindings#1]
For 64-bit simulator builds.

The provided NuGet will link just fine right now, but then will fail when running a 64-bit app in the simulator with an error similar to "The native class has not been loaded yet"

**Comment by alexsorokoletov** [comment]
Hi @deet!
Thank you for the feedback. We're using these bindings for app and haven't seen this problem. Can you add some screenshots and explain in details, please?

**Comment by deet** [comment]
Hi Alex!

Sure, so Xamarin lets the build simulator builds as either 32 bit or 64 bit. You probably won't get the error if it's building for only 32 bit... You customize this in the dialog that looks like:

<img width="766" alt="screen shot 2015-07-13 at 7 00 32 pm 1" src="https://cloud.githubusercontent.com/assets/1018555/8662795/79d5f6ae-2991-11e5-9b2c-8b32ec347f68.png">

The issue is that the static library, the .a file, does not include a x86_64 version, only regular x86:

<img width="875" alt="screen shot 2015-07-13 at 7 01 35 pm" src="https://cloud.githubusercontent.com/assets/1018555/8662813/9d6d7934-2991-11e5-8f35-be279e085af2.png">

(It needs a line that includes "(for architecture x86_64):  current ar archive random library")

You can replicate by setting to x86_64 in the first dialog, and then running the app. The constructor will throw an exception when you try to instantiate an instance of the main overlay class.

I'm happy to provide an example of the exception if you need it! But really all that needs to be done is a recompilation of the static library with x86_64 as an included architecture.

Thanks for the binding!

**Comment by alexsorokoletov** [comment]
Yes, now I see. So we never tested with x64 simulator, you are right.

**Comment by alexsorokoletov** [comment]
Resolved with 7e17da205b66deb53c6bbfb8866d8f45ef4fe657
